<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMAxYwvx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMAxYwvx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMAxYwvx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMAxYwvx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMAxYwvx\App_KernelDevDebugContainer([
    'container.build_hash' => 'MAxYwvx',
    'container.build_id' => '0403fe40',
    'container.build_time' => 1742328345,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMAxYwvx');
